name: Sync Images to Aliyun OSS

on:
  push:
    branches:
      - main  # 监听 main 分支的推送
    paths:
      - '**.jpg'
      - '**.png'
      - '**.jpeg'
      - '**.webp'
workflow_dispatch:  # 加上这一行，开启手动开关
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Sync files to OSS
        run: |
          # 同步图片到阿里云 OSS
          ossutil cp -r . oss://${{ secrets.OSS_BUCKET }}/ -u --include "*.jpg" --include "*.png" --include "*.jpeg" --include "*.webp"

      - name: Success Message
        run: echo "Sync to Aliyun OSS completed successfully!"
